# Generated by Django 4.1.3 on 2022-12-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default=True, max_length=144),
        ),
    ]
